version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    port: 
      - 27017:27017
    volumes:
      - 'mongodb:/data/db'
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: "api"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - redis 
      - mongodb
    depends_on:
      - mongo
      - redis
    environment:
      DATABASE_URL: mongodb://mongodb:27017
      REDIS_URL: redis://redis
    stdin_open: true
    tty: true
#volumes:
  #mongo: