version: '3'
services:
  mongo:
    image: mongo
    port: 
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
  redis:
    image: redis
    ports:
      - '6379:6379'
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: 
    volumes:
      - .:/app
      - /var/run/dokku-daemon:/var/run/dokku-daemon
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mongodb://mongo:27017
      REDIS_URL: redis://redis
    stdin_open: true
    tty: true
volumes:
  mongo: